"""SQLAlchemy ORM model for the Flashcard entity."""

from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, ForeignKey, Integer, Text

from src.database import Base


class Flashcard(Base):
    """Represents a flashcard generated from a module for a specific student.

    Attributes:
        id: Auto-incremented primary key.
        question: The flashcard question text generated by the AI agent.
        answer: The flashcard answer text generated by the AI agent.
        module_id: Foreign key reference to the module this flashcard belongs to.
        student_id: The user ID of the student who requested generation.
        created_at: UTC timestamp recorded when the flashcard is first inserted.
    """

    __tablename__ = "flashcards"

    id = Column(Integer, primary_key=True, index=True)
    question = Column(Text, nullable=False)
    answer = Column(Text, nullable=False)
    module_id = Column(Integer, ForeignKey("modules.id"), nullable=False)
    student_id = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
