"""SQLAlchemy ORM model for the Quiz entity."""

from datetime import datetime, timezone

from sqlalchemy import JSON, Boolean, Column, DateTime, ForeignKey, Integer, String

from src.database import Base


class Quiz(Base):
    """Represents an AI-generated quiz for a module requested by a specific student.

    Attributes:
        id: Auto-incremented primary key.
        title: A concise title generated by the AI agent for the quiz.
        difficulty_level: Difficulty requested by the student
            (one of ``"Easy"``, ``"Medium"``, ``"Hard"``).
        questions: The full list of question dicts stored as a JSON column.
            Each dict contains ``id``, ``text``, ``question_type``, ``options``,
            ``correct_answer``, and ``explanation``.
        module_id: Foreign key reference to the module this quiz belongs to.
        student_id: The user ID of the student who requested generation.
        is_instructor_assigned: Boolean indicating if it's an official teacher quiz.
        created_at: UTC timestamp recorded when the quiz is first inserted.
    """

    __tablename__ = "quizzes"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=False)
    difficulty_level = Column(String, nullable=False, default="Medium")
    questions = Column(JSON, nullable=False)
    module_id = Column(Integer, ForeignKey("modules.id"), nullable=False)
    student_id = Column(Integer, nullable=False)
    is_instructor_assigned = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
