"""SQLAlchemy ORM model for the Summary entity."""

from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Text

from src.database import Base


class Summary(Base):
    """Represents an AI-generated summary for a module requested by a specific student.

    Attributes:
        id: Auto-incremented primary key.
        title: A concise title generated by the AI agent for the summary.
        content: The full summary text generated by the AI agent.
        word_count: Number of words in ``content``, computed at write time.
        summary_level: Comprehension depth requested by the student
            (one of ``"Brief"``, ``"Standard"``, ``"Detailed"``).
        module_id: Foreign key reference to the module this summary belongs to.
        student_id: The user ID of the student who requested generation.
        created_at: UTC timestamp recorded when the summary is first inserted.
    """

    __tablename__ = "summaries"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=False)
    content = Column(Text, nullable=False)
    word_count = Column(Integer, nullable=False)
    summary_level = Column(String, nullable=False, default="Standard")
    module_id = Column(Integer, ForeignKey("modules.id"), nullable=False)
    student_id = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
